title: Movie Mania
email: null@gmail.com
description: "Movie Mania"
baseurl: "/"
url: "https://moviemaniawsp.github.io"
twitter_username: best magisk module
github_username:  best magisk
author:Movie Mania


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
