title: Movie Mania
email: null@gmail.com
description: "Movie Mania"
baseurl: "/"
url: "https://moviemaniawsp.github.io"
twitter_username: moviemaniawsp
github_username:  moviemaniawsp
author: Movie Mania


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
